// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "admin/internal/logic/adapter"
	_ "admin/internal/logic/admin_api"
	_ "admin/internal/logic/casbin_rule"
	_ "admin/internal/logic/enforcer"
	_ "admin/internal/logic/log"
	_ "admin/internal/logic/menu"
	_ "admin/internal/logic/pool"
	_ "admin/internal/logic/role"
	_ "admin/internal/logic/role_menu"
	_ "admin/internal/logic/status"
	_ "admin/internal/logic/token"
	_ "admin/internal/logic/tools"
	_ "admin/internal/logic/tpl"
	_ "admin/internal/logic/user"
)
