// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "admin/internal/logic/token"
	_ "admin/internal/logic/tools"
	_ "admin/internal/logic/tpl"
	_ "admin/internal/logic/user"
)
