// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "admin/internal/logic/tokens"
	_ "admin/internal/logic/tpl"
	_ "admin/internal/logic/users"
)
