// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure of table api for DAO operations like Where/Data.
type Api struct {
	g.Meta    `orm:"table:api, do:true"`
	Id        interface{} //
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 修改时间
	DeletedAt *gtime.Time // 删除时间
	IsDeleted interface{} // 数据的逻辑删除
	Group     interface{} // 分组
	Path      interface{} // 请求路径
	Detail    interface{} // 简介
	Method    interface{} // 请求方式
}
