// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Menu is the golang structure of table menu for DAO operations like Where/Data.
type Menu struct {
	g.Meta      `orm:"table:menu, do:true"`
	Id          interface{} //
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time // 修改时间
	DeletedAt   *gtime.Time // 删除时间
	IsDeleted   interface{} // 数据的逻辑删除
	Title       interface{} // 名称
	Icon        interface{} // 图标
	KeepAlive   interface{} // 是否缓存
	DefaultMenu interface{} // 是否基础路由
	Hidden      interface{} //
	Sort        interface{} //
	ParentId    interface{} //
	Name        interface{} //
	Path        interface{} //
	Component   interface{} //
}
