// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OperationLog is the golang structure of table operation_log for DAO operations like Where/Data.
type OperationLog struct {
	g.Meta    `orm:"table:operation_log, do:true"`
	Id        interface{} //
	UserId    interface{} //
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 修改时间
	DeletedAt *gtime.Time // 删除时间
	IsDeleted interface{} // 数据的逻辑删除
	Status    interface{} // 状态
	Extra     interface{} //
	Ip        interface{} // 请求ip
	Path      interface{} // 请求路径
	Method    interface{} // 请求方法
	Request   interface{} // 请求参数
	Response  interface{} // 响应内容
	Agent     interface{} // 代理
	Latency   interface{} // 延迟
	ErrMsg    interface{} // 错误信息
	UserName  interface{} // 用户名
}
