// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"github.com/casbin/casbin/v2/model"
)

type IAdapter interface {
	LoadPolicy(model model.Model) error
	SavePolicy(model model.Model) (err error)
	AddPolicy(sec string, ptype string, rule []string) (err error)
	AddPolicies(sec string, ptype string, rules [][]string) (err error)
	RemovePolicy(sec string, ptype string, line []string) error
	RemovePolicies(sec string, ptype string, lines [][]string) error
	RemoveFilteredPolicy(sec string, ptype string, fieldIndex int, fieldValues ...string) error
}

var localAdapter IAdapter

func Adapter() IAdapter {
	if localAdapter == nil {
		panic("implement not found for interface IAdapter, forgot register?")
	}
	return localAdapter
}

func RegisterAdapter(i IAdapter) {
	localAdapter = i
}
