// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/casbin/casbin/v2/model"
)

type IAdapter interface {
	LoadPolicy(ctx context.Context, model model.Model) error
	SavePolicy(ctx context.Context, model model.Model) (err error)
	AddPolicy(ctx context.Context, sec string, ptype string, rule []string) (err error)
	RemovePolicy(ctx context.Context, sec string, ptype string, line []string) error
	RemoveFilteredPolicy(ctx context.Context, sec string, ptype string, fieldIndex int, fieldValues ...string) error
}

var localAdapter IAdapter

func Adapter() IAdapter {
	if localAdapter == nil {
		panic("implement not found for interface IAdapter, forgot register?")
	}
	return localAdapter
}

func RegisterAdapter(i IAdapter) {
	localAdapter = i
}
