// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"admin/internal/model"
	"admin/internal/model/entity"
	"admin/internal/model/serializer"
	"context"
	"database/sql"

	"github.com/gogf/gf/v2/frame/g"
)

type IAdminApi interface {
	Count(ctx context.Context) (data int, err error)
	List(ctx context.Context, in model.AdminApiListInput) (items []*serializer.Api, err error)
	InsertAndGetId(ctx context.Context, data g.Map) (id int64, err error)
	Create(ctx context.Context, in *model.AdminApiCreateInput) (id int64, err error)
	Update(ctx context.Context, in model.AdminApiUpdateInput) (row int64, err error)
	Detail(ctx context.Context, in model.AdminApiDetailInput) (data *serializer.Api, err error)
	Delete(ctx context.Context, in model.AdminApiDeleteInput) (result sql.Result, err error)
	SafeDelete(ctx context.Context, r *model.OrmDeleteInput) (row int64, err error)
	Save(ctx context.Context, in *entity.Api) (result sql.Result, err error)
}

var localAdminApi IAdminApi

func AdminApi() IAdminApi {
	if localAdminApi == nil {
		panic("implement not found for interface IAdminApi, forgot register?")
	}
	return localAdminApi
}

func RegisterAdminApi(i IAdminApi) {
	localAdminApi = i
}
