// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"admin/internal/model"
	"admin/internal/model/entity"
	"admin/internal/model/serializer"
	"context"
	"database/sql"

	"github.com/gogf/gf/v2/frame/g"
)

type ICasbinRule interface {
	Count(ctx context.Context) (data int, err error)
	List(ctx context.Context, in model.CasbinRuleListInput) (items []*serializer.CasbinRule, err error)
	InsertAndGetId(ctx context.Context, data g.Map) (id int64, err error)
	Create(ctx context.Context, in *model.CasbinRuleCreateInput) (id int64, err error)
	Update(ctx context.Context, in model.CasbinRuleUpdateInput) (row int64, err error)
	Detail(ctx context.Context, in model.CasbinRuleDetailInput) (data *serializer.CasbinRule, err error)
	Delete(ctx context.Context, in model.OrmDeleteInput) (result sql.Result, err error)
	Save(ctx context.Context, in *entity.CasbinRule) (result sql.Result, err error)
}

var localCasbinRule ICasbinRule

func CasbinRule() ICasbinRule {
	if localCasbinRule == nil {
		panic("implement not found for interface ICasbinRule, forgot register?")
	}
	return localCasbinRule
}

func RegisterCasbinRule(i ICasbinRule) {
	localCasbinRule = i
}
