// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"admin/internal/model"
	"context"
)

type IPool interface {
	Invoke(ctx context.Context, r *model.LogCreateInput)
	Jobs() int
	Cap() int
	Size() int
	Add(ctx context.Context, f func(ctx context.Context)) error
	Idea() int
	Show(ctx context.Context)
}

var localPool IPool

func Pool() IPool {
	if localPool == nil {
		panic("implement not found for interface IPool, forgot register?")
	}
	return localPool
}

func RegisterPool(i IPool) {
	localPool = i
}
