// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"admin/internal/model"
	"context"
)

type IToken interface {
	GenAccessToken(ctx context.Context, r *model.TokenServiceGenTokenReq) (token string, err error)
	GenToken(ctx context.Context, uid string, exp int64) (token string, err error)
	CheckToken(ctx context.Context, token string) (uid string, err error)
}

var localToken IToken

func Token() IToken {
	if localToken == nil {
		panic("implement not found for interface IToken, forgot register?")
	}
	return localToken
}

func RegisterToken(i IToken) {
	localToken = i
}
