// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type ITools interface {
	Captcha(ctx context.Context) (id, b64s string, err error)
	Verify(ctx context.Context, captchaId, captcha string, clear bool) (ok bool)
}

var localTools ITools

func Tools() ITools {
	if localTools == nil {
		panic("implement not found for interface ITools, forgot register?")
	}
	return localTools
}

func RegisterTools(i ITools) {
	localTools = i
}
