// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type ITpl interface {
	Logout(ctx context.Context) error
}

var localTpl ITpl

func Tpl() ITpl {
	if localTpl == nil {
		panic("implement not found for interface ITpl, forgot register?")
	}
	return localTpl
}

func RegisterTpl(i ITpl) {
	localTpl = i
}
