// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RoleMenu is the golang structure for table role_menu.
type RoleMenu struct {
	Id        int         `json:"id"        ` //
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 修改时间
	DeletedAt *gtime.Time `json:"deletedAt" ` // 删除时间
	IsDeleted int         `json:"isDeleted" ` // 数据的逻辑删除
	RoleId    int         `json:"roleId"    ` // 角色id
	MenuId    int         `json:"menuId"    ` // 菜单id
}
