// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id         int         `json:"id"         ` //
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 修改时间
	IsDeleted  int         `json:"isDeleted"  ` // 数据的逻辑删除
	Name       string      `json:"name"       ` //
	Password   string      `json:"password"   ` //
	Nickname   string      `json:"nickname"   ` //
}
